### ISSUE TITLE
Local build fails because version is not being handled

### ISSUE THREAD

**Issue by Kav91** [newrelic/nri-flex#105]
When building a binary locally Flex throws:

`time="2020-02-21T16:24:18-08:00" level=fatal msg="flex: failed to initialize integration" error="flex: failed to create integration integration version cannot be empty"`

In the past this was never the case, it would attach the git sha, and hyphenate with dirty if required.
The version handling needs to be reverted to the prior way it was handled so local dev/testing is not blocked.

**Comment by ardias** [comment]
@Kav91 Can you try again? I was aware and had a fix in a PR. I merged it, should fix the local build

**Comment by Kav91** [comment]
@ardias I tried but the behaviour is not the same.
It always puts `Unknown-SNAPSHOT` as the version when it should be using the git sha and flagging dirty when needed.

**Comment by ardias** [comment]
Yes, when using local compilation it does that. When it is released the version is set at the release version.
We prefer that released version are used,  but do you have a use-case for setting it as the git sha on a local compiled version?

**Comment by Kav91** [comment]
Yes, because when you are creating test releases you can quickly understand and see what version you or a customer is running. It's been extremely useful and critically when debugging. 
Without it we can't reliably figure this out and track correctly.
