### ISSUE TITLE
Create include_filter and exclude_filter functions

### ISSUE THREAD

**Issue by 2michaelhammond** [newrelic/nri-flex#114]
The sample_filter function skips creating the sample (i.e. **exclude_filter**).  This is great for static data sets or when you only need to filter out a few things.  If I am only interested in one key and one value, an option to have an **include_filter** would be ideal.  This would be a better option if the data sets are dynamic (i.e. new values are added all the time) or there are many values (i.e. 1000 unique values).

**Comment by ardias** [comment]
@2michaelhammond Can you provide an example of how this would look like?

**Comment by 2michaelhammond** [comment]
I have an API query that returns "name" : "string" and there are 1000 potential values of $name (i.e. st1, stri2, bob, john, dave, ...string1000).  I then need create a store_lookup on $name and only need to pass "string1" to second API call.  Using the sample_filter, I can exclude 999 $name values or it would just be easier to include one "$string" value and exclude the rest.  If new $name values pop up, I would then need to always update the sample_filter configuration.

"name": "string"
"name": "string"
"name": "string"
"name": "string"
