### ISSUE TITLE
Add search and replace functionality

### ISSUE THREAD

**Issue by 2michaelhammond** [newrelic/nri-flex#115]
I was in need of transforming a string (value) by doing a replacement of one of the characters.  The value_transformer function only allows you to append to an existing value and not do a replace.  Notes from Kav on this: "I feel that we should rework value transformer or maybe this could just be a new function, to target regex groups, then you supply an array of values that will be used to substitute each group."

**Comment by haihongren** [comment]
@2michaelhammond 

We have a **value_mapper** function, which is not documented yet. 
The syntax looks like follows, please test it and let us know whether this  helps.

```json
  value_mapper:
      title:
        - (Service Status)=>Normal
        - (Informational message)=>$1 - Warning
        - (Service degradation)=>$1 - Warning
        - (Service disruption)=>$1 - Down
        - (Service is operating normally)=>$1 - Normal
```
Where, 
* title -> the attribute
* it supports a list of regex patterns and regex group replacement
