### ISSUE TITLE
Events not loading from windows host

### ISSUE THREAD

**Issue by nrim** [newrelic/nri-flex#128]
I'm working through the tutorial, and I'm not seeing anything in NR insights.

Host Infrastructure agent: 1.11.4

Created `integrations.yml` in `C:\Program Files\New Relic\newrelic-infra\integrations.d\`

File contains what is in the tutorial:

```yaml
integrations:
  - name: nri-flex
    config:
      name: just-testing
```

No events show in in New Relic Insights when i try NSQL `FROM flexStatusSample SELECT * LIMIT 1`

I've turned on verbose logging for the agent and I get this error:

```
time="2020-03-24T23:39:33Z" level=debug msg="Found integration config file" component=PluginRegistry configFile="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\integrations.yml"
time="2020-03-24T23:39:33Z" level=debug msg="Ignoring v4 integration. To be loaded later." component=PluginRegistry file="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\integrations.yml"
```

I can't find what the reference to v4 integration means. Any help would be appreciated.

**Comment by thezackm** [comment]
hi @nrim , can you run the following in CMD (not PowerShell) and show the output here please?

`"C:\Program Files\New Relic\newrelic-infra\newrelic-integrations\nri-flex.exe" --verbose`

**Comment by nrim** [comment]
I found the problem... nri-flex.exe is not part of the Infrastructure agent install on windows.  dropping it in place fixed the issue.

**Comment by ardias** [comment]
Hi @nrim Yes, we didn't package it as it wasn't in the official supported platforms. It should be available next week as we are starting work on validating windows support.
In the meantime you can just download the executable from the releases page and put it in **c:\program files\new relic\newrelic-infra\newrelic-integrations** and it should work
