### ISSUE TITLE
split_by needs to be documented

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-flex#138]
The **split_by** function exists in many example configs, however, it is not mentioned in the docs.

**Comment by theletterf** [comment]
From what I gather, `split_by` accepts a list of expressions for splitting separate entries in the data under `sub_parse`, and it applies to command apis only. It accepts regex when `regex_match` is true. Going to document that in a docs branch for a PR.

**Comment by theletterf** [comment]
It's documented in `commands.md`, @bpschmitt !
