### ISSUE TITLE
Additional Supporting Details

### ISSUE THREAD

**Issue by ntcsteve** [newrelic/nri-flex#145]
Hi there, I posted privately to the FLEX original creator and he suggested me to post here for further improvements. 

1. It's probably a good idea to expand more on examples especially regular expression. 
For example, here is the cmd, here is the output, and how this regex will perform to put the data into NR? 

2. Please put a prerequisite knowledge required to get FLEX working. This is targeted predominantly for traditional ops persona who might not having strong DevOps skillset. 

3. How do you check if the integration is done correctly? how does failure looks like?

4. Offer basic troubleshooting tips to check if FLEX is working correctly. 

5. The more examples we have, the better it is the adoption will be and more people can use it to develop their own integration.

**Comment by thezackm** [comment]
@Kav91 - are we at a point where we can re-visit updating the organization of the `/examples` directory?

**Comment by theletterf** [comment]
Thanks - excellent feedback!

I'm working on a separate branch where most of your concerns are addressed. See, for example: https://github.com/newrelic/nri-flex/blob/docs-for-ga/docs/troubleshooting.md

**Comment by ntcsteve** [comment]
Here is a nice article on Regex - https://levelup.gitconnected.com/read-this-if-you-dont-know-enough-about-regex-73141bb0e1a7
