### ISSUE TITLE
experimental command declarations 

### ISSUE THREAD

**Issue by jcoope02** [newrelic/nri-flex#178]
currently the examples given that have experimental features or commands do not declare that. For example the port test example (https://github.com/newrelic/nri-flex/blob/master/examples/flexConfigs/port-test-example.yml) uses the -dial command. If I am missing the dependencies it will not work and will never know why and end up wasting time trouble shooting. On top of that it if you go to the command docs (https://github.com/newrelic/nri-flex/blob/master/docs/apis/commands.md) -dial is not there. Would nice to have it there, but listed as experimental so that I can know how it works, what it does and the dependencies. 

In any case people should know in advance if they are using some thing that is not GA

**Comment by theletterf** [comment]
@ardias @Kav91 @thezackm We should either add a comment to examples using experimental features, or move them to an `experimental` subfolder.

**Comment by thezackm** [comment]
i think a comment makes the most sense; assumption is there are examples that have both supported and experimental functions in play right now. can we get a mtg scheduled to outline the reorg of the examples directory? I can make myself available to fit schedules; just toss up some times against my calendar and let's kick this bucket!

**Comment by thezackm** [comment]
resolved with PR #185
