### ISSUE TITLE
The function precedence order is gone

### ISSUE THREAD

**Issue by mikebryant** [newrelic/nri-flex#188]
As of fac30f0263fa29fccbbe07263dca3b3742ecbc25 the https://github.com/newrelic/nri-flex/blob/master/docs/basics/functions.md#function-precedence-order is just a copy of the table of contents, and doesn't detail function precedence at all

**Comment by ardias** [comment]
Hi @mikebryant sorry about that. It slipped under the radar. I've opened a PR to fix it

**Comment by mikebryant** [comment]
I see #189 has been merged and fixes this, looks great. Thanks for the quick response :)
