### ISSUE TITLE
HTTP request handling broken during refactor

### ISSUE THREAD

**Issue by Kav91** [newrelic/nri-flex#206]
Internal discussion: https://newrelic.slack.com/archives/CPVCA6Y86/p1596379457402500?thread_ts=1596373059.401200&cid=CPVCA6Y86

Automatic pagination walk is no longer working as expected which breaks how normal http functionality should work as there are missing payloads from the initial request.  
eg. looks like it ignores the initial results, and are not appended and you just get the last set.

I reverted to my prior http code which was before GA, and everything worked as expected.  Haven't figured out which changes caused this issue.

**Comment by Kav91** [comment]
@Noly are you able to have a look plz? As #180 was the biggest change to how the http functionality worked recently. I'm assuming its related but could be wrong.

Also would be good if we can get on this early as Mike has a live test case that can be used to validate against.

**Comment by Noly** [comment]
Hi @Kav91 thanks for raising this up. We added it on our queue and we will working on this ASAP

**Comment by Noly** [comment]
A new version of Flex [v1.3.5](https://github.com/newrelic/nri-flex/releases/tag/v1.3.5) was released with the fix for this issue.

Thanks for your feedback.
