### ISSUE TITLE
error in clock-drift-ntp integration

### ISSUE THREAD

**Issue by sibuskariah** [newrelic/nri-flex#209]
Error:

time="2020-08-06T06:45:22-05:00" level=warning msg="can't instantiate integrations from file" component=integrations.Manager error="can't instantiate integration: can't find an executable given the name: nri-flex" file="C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\clock-drift-ntp.yml"

clock-drift-ntp.yml content:

------------------
---
integrations:
  - name: nri-flex
    config:
      name: clockDriftNTP
      apis:
        - name: clockDriftNTP
          shell: powershell
          commands:
            - run: "w32tm /stripchart /computer:pool.ntp.org /samples:1 /dataonly"

-------------------

Any help is greatly appreciated

Thanks
Sibu Skariah

**Comment by thezackm** [comment]
can you please provide the YAML configuration you are using in a [markdown config block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) so that formatting is maintained?

additionally, what version of the New Relic infrastructure agent, and what version of Windows are you attempting to run this on?

**Comment by sibuskariah** [comment]
nri-flex was missing in the integration.d path. So installed the latest version of infra agent and the flex integration is send data to Insight.

But i am getting following error when try running the command on the server. But local machine its working

C:\Windows\system32>w32tm /stripchart /computer:pool.ntp.org /samples:3 /dataonly                                                                               Tracking pool.ntp.org [136.243.202.118:123].                                    
Collecting 3 samples.                                                          
The current time is 8/18/2020 5:11:23 AM.                                       
05:11:23, error: 0x800705B4                                                    
05:11:26, error: 0x800705B4                                                     
05:11:29, error: 0x800705B4                                                                                                                                     C:\Windows\system32>

**Comment by thezackm** [comment]
closing with PR #226
