### ISSUE TITLE
Different behaviours for Powershell

### ISSUE THREAD

**Issue by ronnh** [newrelic/nri-flex#216]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
I have two different `integrations.yaml` configuration to run a Power-shell script but the behaviour is different for each configuration.
## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
First Configuration:
I saw this configuration from some older issues, but one of the issues with this configuration is that the file pathing does not accept spaces. I would need to run the Power-Shell script in the New Relic Infra Agent folder, but the space between `Program Files` is not allowing me.

```
apis:
        - name: Tm1Validation
          commands:
            - run: powershell -file C:\validation.ps1
```

**Edit:** This actually doesn't work perfectly yet, it still gives an exit status 1 but I can see the output of it in error_message. The output is just jumbled up.

Second Configuration:
This is the newer configuration that i saw in some of the examples, but the problem with this configuration is that for some of the machines, it'll just give an error of `exit status 1` with no error message. So i'm not even sure whats wrong with that. The Power-Shell script works fine when I'm running it locally. I have also gone through the logs with `verbose: 1` option in the infra agent configuration yaml.

```
apis:
        - name: Validation
          shell: powershell
          commands:
            - run: "& \"C:/Program Files/New Relic/newrelic-infra/integrations.d/validation.ps1\""
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
I expect both of these configurations to behave the same and for the second configuration to work for all machines.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
This is the only relevant logs that I found when using the second configuration from `verbose: 1`.

```
time="2020-08-24T21:35:52Z" level=debug msg="time=\"2020-08-24T21:35:52Z\" level=debug msg=\"command: failed\" err=\"exit status 1\" exec=\"& \\\"C:/Program Files/New Relic/newrelic-infra/integrations.d/validation.ps1\\\"\" suggestion=\"if you are handling this error case, ignore\"" component=integrations.runner.Group integration_name=nri-flex
time="2020-08-24T21:35:52Z" level=debug msg="time=\"2020-08-24T21:35:52Z\" level=debug msg=\"processor-data: running data handler\" name=flexIntegrations" component=integrations.runner.Group integration_name=nri-flex
time="2020-08-24T21:35:52Z" level=debug msg="time=\"2020-08-24T21:35:52Z\" level=debug msg=\"config: finished variable processing apis\" apis=1 name=flexIntegrations" component=integrations.runner.Group integration_name=nri-flex
time="2020-08-24T21:35:52Z" level=debug msg="time=\"2020-08-24T21:35:52Z\" level=info msg=\"flex: completed processing configs\" configs=1" component=integrations.runner.Group integration_name=nri-flex
```
Whats weird to me is the first line of log where it's talking about some kind of error, but I don't see any error logs at all.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
This was done with a power-shell validation script.

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
All the machines are running Windows Server 2012 with Infrastructure agent version `1.12.1`

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by thezackm** [comment]
this experience is a function of PowerShell itself, not something that is happening in Flex. 

Using [PowerShell.exe with -File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-file----filepath-args) executes the target script in the [local scope](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_scopes?view=powershell-5.1#powershell-scopes), which will natively have access to any and all errors during script execution.

Using a [Call Operator](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7#call-operator-) `& ".\script path\script.ps1"` executes the script in a child scope, and the errors within that scope are not natively passed into the call operator's view without you explicitly adding a [throw](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_throw?view=powershell-7).

**Comment by thezackm** [comment]
closing issue - behavior is expected based on how PowerShell itself works and can be adjusted by the execution method in the `run` config element
