### ISSUE TITLE
Add go snowflake driver to flex binary - enabling the database API to be used with snowflake.

### ISSUE THREAD

**Issue by danifitz** [newrelic/nri-flex#256]
## Is your feature request related to a problem? Please describe.
Currently flex can execute queries directly with MySql, Postgres etc. I'd like the same functionality available for Snowflake, which is a very popular data warehousing solution that many customers are adopting

## Feature Description
The ability to use the database API to query Snowflake. To achieve this, the go snowflake driver would need to be included in flex.

## Describe Alternatives
I've already got a flex integration that uses an external Node.js script that uses the node snowflake driver, but this setup is more complex than it should be.

## Additional context
None

## Priority
Really want.

**Comment by josemore** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
