### ISSUE TITLE
Add information on how to test flex integrations locally to the troubleshooting documentation.

### ISSUE THREAD

**Issue by nephyst** [newrelic/nri-flex#260]
## Is your feature request related to a problem? Please describe.
Nope

## Feature Description
https://github.com/newrelic/nri-flex/blob/master/docs/troubleshooting.md

I was having issues with a flex integration and after going through the getting started and troubleshooting docs I was not aware that it was possible to test flex integrations locally. Having information about how to test locally to the troubleshooting section would have been incredibly helpful.

## Priority
Nice to have

**Comment by thezackm** [comment]
fixed with PR #261
