### ISSUE TITLE
Markdown table is broken in nri-flex/docs/apis/commands.md

### ISSUE THREAD

**Issue by matthewmrichter** [newrelic/nri-flex#267]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
The table on this page is unreadable.

## Description
<img width="1162" alt="Screen Shot 2021-01-24 at 3 04 11 PM" src="https://user-images.githubusercontent.com/4481324/105642083-81edab80-5e55-11eb-9854-dd98ff3fa1f1.png">

## Expected Behavior
Human readable table

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by thezackm** [comment]
fixed with PR #274
