### ISSUE TITLE
Native support of CSV from a HTTP response

### ISSUE THREAD

**Issue by mikeylee** [newrelic/nri-flex#273]
## Is your feature request related to a problem? Please describe.
I'm trying to ingest the Salesforce logfile data for the EVENTTYPE = 'ApexUnexpectedException' using Flex.
All other event types like  LightningPerformance, LightningPageView and VisualforceRequest, to name a few, we are able to use Flex to do the initial RESTAPI call and then run a Curl command to retrieve the individual logfile data for the EVENTTYPE and parse it and write to the NR schemas fine.
Unfortunately, we ran into an issue with parsing the logfile data for the EVENTTYPE of 'ApexUnexpectedException' using the attached YML file.
The issue is that the http response from Curl contains CSV and the vendor  has used a non standard method of spreading a data row over several lines with each line ending in a CR\LF.  If we look closely, It is the Exception message field which is being broken up and spread over several lines, each ending with a CR\LF.     The standard however, is to have comma delimited fields with a single CR\LF at the end of the data row.   

See attached YML file and Curl response.
## Feature Description
Request to have Flex natively support CSV  in a HTTP response, as already done with JSON.

## Describe Alternatives
We have use the attached YML file to process other salesforce  event types sucessfully.

## Additional context
None

## Priority
Blocker - Salesforce is becoming widely used and would be good if Flex could deal with CSV from HTTP responses natively.

[ApexUnexpectedExcept.zip](https://github.com/newrelic/nri-flex/files/5956062/ApexUnexpectedExcept.zip)

**Comment by haihongren** [comment]
@mikeylee The CSV support feature has been added/merged into master. 
It will be available when the next build is released.  

At the mean time, you can compile a temp build yourself from the master branch.  
Please reach out again if you need further assistance.

I will close this issue now.

Thanks,
Haihong
