### ISSUE TITLE
Create system packages like all the other NRI plugins

### ISSUE THREAD

**Issue by gregbuehler** [newrelic/nri-flex#28]
While `sudo bash -c "$(curl ...)"` sounds fun it's not exactly supported practice for most companies.

Can we get some deb's and rpm's in http://download.newrelic.com/infrastructure_agent/linux to facilitate installation?

**Comment by Kav91** [comment]
Hi @gregbuehler, thanks for raising. The sudo bash approach is a good alternative for beginners, and is still widely used, and being able to spike something quickly allows for fast time to value. 
For those more conscious of its behaviour like yourself, compiled releases are provided as an alternative already. 

Our infrastructure team is working towards productizing Flex, and this would likely include debs & rpms like our other integrations. So for now I'd suggest grabbing one of the compiled releases, and we'll have some packages coming down the track. 

Will close for now, as theres an alternative and something on our radar already.
