### ISSUE TITLE
NRIFlex with SQL server database - "failed to connect to DBus. make sure systemd is present."

### ISSUE THREAD

**Issue by ngdonna2020** [newrelic/nri-flex#288]
Hi, I am trying to build New Relic integration for Microsoft SQL Server database. I cloned the repository from another project that is working fine but it was using MySQL so in the **examples** folder, I followed the **sqlserver-database-examples.yml** :
[https://github.com/newrelic/nri-flex/blob/master/examples/sqlserver-database-example.yml](https://github.com/newrelic/nri-flex/blob/master/examples/sqlserver-database-example.yml) and change the db_conn and db_queries variable to be fitting for my case:
`# ref: https://github.com/newrelic/nri-flex/blob/master/docs/experimental/db.md
integrations:
  - name: nri-flex
    config:
      name: sqlserverDbFlex
      apis:
        - database: sqlserver
          db_conn: server=myserver.com;user id=hithere;database=master;encrypt=disable;password=byethere
          logging:
            open: true
          custom_attributes: # applies to all queries
            host: myDbServer
          db_async: true # process queries async
          db_queries:
            - name: sqlserverExecSample
              run: Select count(*) from dbo.ABC
              custom_attributes: # can apply additional at a nested level
                nestedAttr: nestedVal`

I also had to adjust the environmental variables from the previous MySQL project to this SQLserver project but it s giving me these messages: 
 _level=debug msg="database: ping error" database=sqlserver err="<nil>" name=sqlserverDbFlex
 level=warning msg="failed to connect to DBus. make sure systemd is present." component=NotificationHandler
level=warning msg="failed to init shutdown monitor" component=NotificationHandler error="no systemd found_

I am not sure if this is because the yml file i had replaced as above or maybe some other issue i need to look elsewhere in the code repository? Thank you for any input

**Comment by josemore** [comment]
thanks for raising this @ngdonna2020 
Any level=error on the logs?

You can troubleshoot your Flex config as shown in the docs: https://github.com/newrelic/nri-flex/blob/753e0db2326f451a158d3fca03afd38922ec6370/docs/troubleshooting.md#testing-a-config

**Comment by ngdonna2020** [comment]
Hello, no level=error. Im only seeing level=info, level=warning or level=debug

**Comment by Kav91** [comment]
These two messages are not from Flex:
```
level=warning msg="failed to connect to DBus. make sure systemd is present." component=NotificationHandler
level=warning msg="failed to init shutdown monitor" component=NotificationHandler error="no systemd found
```

The ping error is logged from Flex, and that can occur if the database is not reachable.
