### ISSUE TITLE
uptime doesn't work on RHEL

### ISSUE THREAD

**Issue by newtob** [newrelic/nri-flex#312]
## Description
the linux-uptime.yml does not work for RHEL 7. It's using a GREP that doesn't work for the commands output. It greps for "System uptime", but this isn't output on the RHEL version of the uptime command. Instead it just states "3 days" as the 3rd and 4th entries:
https://github.com/newrelic/nri-flex/blob/master/examples/linux/linux-uptime.yml

## Expected Behaviour
Our hope is that it would show the uptime of RHEL 7 systems. for example in days.

## Your Environment
RHEL 7, running the New Relic Infrastructure agent 1.19.3

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
