### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by rabiul25** [newrelic/nri-flex#319]
Docker build is getting failed due to non availability of bin folder in the project.
COPY ./bin/linux/nri-flex /var/db/newrelic-infra/newrelic-integrations/bin/
Please advice where the the contains of bin folder can be found.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
