### ISSUE TITLE
Need to get the Computational memory percentage for AIX server

### ISSUE THREAD

**Issue by Pritamdey148** [newrelic/nri-flex#323]
Computational memory percentage for AIX server is mandatory 

We need to create alert for Computational memory percentage for AIX server

In AIX servers according to IBM if the computational Memory reached 98% and started to page highly only we need to worry about the memory in AIX LPARs.

**Comment by josemore** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution given AIX is not officially supported on the Infrastructure Agent. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.
