### ISSUE TITLE
Hana Database with Flex integration

### ISSUE THREAD

**Issue by praneeth057** [newrelic/nri-flex#330]
## Is your feature request related to a problem? Please describe.
We are using flex integration to monitor the on-host HANA database in the New Relic. As per the integration document and the configuration of HANA database monitoring, we require a user to enable monitoring. However, we are unable to find the user role, and authorization details to which the user requires access are nowhere mentioned in the documents available online. 

## Feature Description
Please help us with the user role and authorization details to which the user requires access to enable monitoring.

## Additional context
https://github.com/newrelic/nri-flex/blob/master/examples/hana-database-example.yml

## Priority
Blocker

**Comment by josemore** [comment]
Hi @praneeth057, do you still need support with this example?
Note this is using the DB experimental feature and we can't support all the examples we receive from contributors. Unfortunately, we don't have a Hana environment we can use for troubleshooting. 
You might reach for further assistance from the community at the [Explorers Hub](https://discuss.newrelic.com/).
