### ISSUE TITLE
powershell :returns 'nil'

### ISSUE THREAD

**Issue by annbabich** [newrelic/nri-flex#34]
I'm running into an issue where $_CreationTime, $._FullName, or any other obj I try to use  return 'nil'

$filePattern = "*.db"
 $createtime = $filePattern.CreationTime

$directory | Get-ChildItem -Recurse | Where-Object { $_.PsIsContainer -eq $false -and $_.Name -like $filePattern} | Measure-Object | Select-Object -Property @{ expression = { $directory }; name = "directoryName" },@{ expression = { $_.FullName}; name = "fileName" },@{ expression = { $filePattern }; name = "filePattern" },@{ expression = { $_.Count }; name = "fileCount" },@{ expression = { $createtime}; name = "createtime" } | ConvertTo-Json

Here is new relic agent output:
 level=warning msg="cannot handle plugin output" data prefix=integration/com.newrelic.nri-flex error="json: cannot unmarshal array into Go value of type externalPlugins.PluginOutputIdentifier" plugin name=nri-flex

Thanks in advance

**Comment by Kav91** [comment]
hi @annbabich are you able to run flex manually with the -verbose flag, to get some additional output? Also any detail in regards to what is defined in your flex config would be very helpful.

**Comment by Kav91** [comment]
Hi @annbabich are you able to share your Flex config or any further details on this issue?
I'll leave the issue open for a few more days.

**Comment by annbabich** [comment]
@Kav91 , 
I got configuration working with outside help. I will share it here. Standby.

**Comment by Kav91** [comment]
Issue should be resolved in the GA 1.0.0 release in Flex. You are able to specify the shell in your Flex config and pass it eg. powershell which also helps to avoid any escaping issues.
