### ISSUE TITLE
Windows NTP clock drift data not parsing correctly in New Relic

### ISSUE THREAD

**Issue by travisroberts-sf** [newrelic/nri-flex#350]
## Description
The Windows NTP Clock Drift integration looks like its collecting data from the local host correctly and forming it correctly into a json payload, but when it arrives in New Relic the data is not being correctly parsed.

## Expected Behavior
Windows NTP Clock skew data is ingested into New Relic

## Steps to Reproduce
1. Create the windows-clock-drift-ntp-script.ps1 script under 'C:\Program Files\New Relic\newrelic-infra\integrations.d\flexAssets\ntpCheck.ps1'
2. Create the windows-clock-drift-ntp.yml under 'C:\Program Files\New Relic\newrelic-infra\integrations.d\windows-clock-drift-ntp.yml'
3. Restart the agent
4. In New Relic navigate to the browser and look for ntpCheck event data.
5. Take note that the data is not showing up correctly.  See attached screen shot.

## Your Environment
- Agent Version: 1.24.0
- OS Version:  Windows 2016 VM

## Additional context
Screen Shot attached
<img width="428" alt="2022-04-18_14-29-26" src="https://user-images.githubusercontent.com/70233319/164037842-20ca78e0-9191-4020-9e0b-67c05a12ebc0.png">

**Comment by travisroberts-sf** [comment]
Just wanted to add a little more input to this.  I was able to get some verbose output from this integration.  Unless I'm mistaken, everything looks ok here.  Note I've replace a few host names is hash characters for anonymity:
` PS C:\Program Files\New Relic\newrelic-infra> .\newrelic-integrations\nri-flex.exe --verbose --pretty --config_file .\integrations.d\nrelc-clock-drift-ntp.yml
.\newrelic-integrations\nri-flex.exe : time="2022-05-24T09:21:20-07:00" level=debug msg="Function.isAvailable: enter"
At line:1 char:1
+ .\newrelic-integrations\nri-flex.exe --verbose --pretty --config_file ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (time="2022-05-2...ailable: enter":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
time="2022-05-24T09:21:20-07:00" level=debug msg="Function.isAvailable: exit status: false"
time="2022-05-24T09:21:20-07:00" level=info msg=com.newrelic.nri-flex GOARCH=amd64 GOOS=windows version=1.4.4
time="2022-05-24T09:21:20-07:00" level=debug msg="config: git sync configuration not set"
time="2022-05-24T09:21:20-07:00" level=warning msg="config: testing agent config, agent features will not be available"
time="2022-05-24T09:21:20-07:00" level=debug msg="config: running async" name=ntpCheck
time="2022-05-24T09:21:20-07:00" level=debug msg="config: processing apis" apis=1 name=ntpCheck
time="2022-05-24T09:21:20-07:00" level=debug msg="fetch: collect data" name=ntpCheck
time="2022-05-24T09:21:20-07:00" level=debug msg="commands: executing" count=1 name=ntpCheck
time="2022-05-24T09:21:21-07:00" level=debug msg="processor-data: running data handler" name=ntpCheck
time="2022-05-24T09:21:21-07:00" level=debug msg="config: finished variable processing apis" apis=1 name=ntpCheck
time="2022-05-24T09:21:21-07:00" level=info msg="flex: completed processing configs" configs=1
{
	"name": "com.newrelic.nri-flex",
	"protocol_version": "3",
	"integration_version": "1.4.4",
	"data": [
		{
			"metrics": [
				{
					"event_type": "ntpCheck",
					"integration_name": "com.newrelic.nri-flex",
					"integration_version": "1.4.4",
					"localTime": 1653384081,
					"ntpServer": "##########",
					"skewSign": "+",
					"skewString": 0.0002347,
					"skewValue": 0.000235
				},
				{
					"event_type": "flexStatusSample",
					"flex.Hostname": "############",
					"flex.IntegrationVersion": "1.4.4",
					"flex.counter.ConfigsProcessed": 1,
					"flex.counter.EventCount": 1,
					"flex.counter.EventDropCount": 0,
					"flex.counter.ntpCheck": 1,
					"flex.time.elaspedMs": 986,
					"flex.time.endMs": 1653409281495,
					"flex.time.startMs": 1653409280509
				}
			],
			"inventory": {},
			"events": []
		}
	]
}

PS C:\Program Files\New Relic\newrelic-infra>  
`

**Comment by rogercoll** [comment]
Hi @travisroberts-sf ,

By defualt, the agent did not pass any system environment variable to the integrations executions till release [1.24.3](https://github.com/newrelic/infrastructure-agent/releases/tag/1.24.3), from that version the agent adds some of the common environment variables in the execution. See discussion: https://github.com/newrelic/infrastructure-agent/issues/1115

The script might be using some system env variable, I would recommend upgrading the agent to the latest version and verify if the issue persist. In addition, any addition environment variable can be added in the integrations execution with the [passthrough_environment configuration option](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#passthrough_-environment).

**Comment by travisroberts-sf** [comment]
I am to understand then, that by not passing environment variables, this integration was sending messed up information (per my screenshot attached above)?

**Comment by rogercoll** [comment]
The execution environment is different whether nri-flex it is run by the infra-agent or with powershell (output you provided). As pointed in the previous comment, the main difference is the environment variables used in the execution scenarios, that's why a possible issue would have been that the script produced an error while being run by the agent and you see different information in New Relic. The script error **could be** related to the environment variables.

Let us know if the latest infra-agent solves the issue.

Thanks

**Comment by travisroberts-sf** [comment]
I'll upgrade an agent and let you know later today.  Thanks for the clarification.

**Comment by travisroberts-sf** [comment]
It looks like upgrading works.  I upgraded a couple agents to 1.26.0 and i'm not seeing any of the jumbled up data any more.  What's more, I see valid skew data.

**Comment by rogercoll** [comment]
Sounds great, closing the issue.

Thanks for the feedback.
