### ISSUE TITLE
Add automatic time server discovery for Windows NTP Clock Drift integration

### ISSUE THREAD

**Issue by travisroberts-sf** [newrelic/nri-flex#351]
## Is your feature request related to a problem? Please describe.
Not directly.  In trying to troubleshoot this issue:  https://github.com/newrelic/nri-flex/issues/350 I decided to modify the script temporarily to locate the configured time server.  Turned out that it was a very easy modification.

## Feature Description
Change the $ntpServer variable to use the locally configured time server of the host the integration is running on.  The Windows Clock NTP drift integration currently has the time server hard coded in the powershell script.  With a couple of quick changes this could easily use the configured time server of the host the integration is running on, as most companies tend to use their own internal time servers.
The following two lines of code are what would need to change:
```
$server = [Net.Dns]::GetHostName()
$ntpServer = w32tm /query /computer:$server /source | Out-String
```
## Describe Alternatives
The alternative is to do nothing and continue letting users manually update the powershell script with the correct time server.  However, in larger organizations, this can be troublesome as often there are multiple geographically located time servers.

## Priority
Nice to have

**Comment by rogercoll** [comment]
Hi @travisroberts-sf , can we close this issue? 

The suggested lines were added in https://github.com/newrelic/nri-flex/pull/357
