### ISSUE TITLE
reuse of nagios scripts and catch exit code

### ISSUE THREAD

**Issue by sdeedee** [newrelic/nri-flex#36]
Hi,

I want to reuse some old nagios scripts in nri-flex without the need of the nri-nagios ohi. The script is returning an output message and an exit code. 

DEBU[0000] command: failed                               err="exit status 3" exec="/usr/lib64/cmbmonit/plugins/check_load -w 5,3,2 -c 0,6,4" suggestion="if you are handling this error case, ignore"
DEBU[0000] command: running /usr/lib64/cmbmonit/plugins/check_load -w 5,3,2 -c 0,6,4

I want to catch the whole output of the command but I can't make it work. I'm not sure if it's related to the exit code the script is throwing or wrong syntax. 

Can someone points me to the wright direction?

Thanks!

**Comment by haihongren** [comment]
are you able to share the output of the script? what format is it? thanks!

**Comment by sdeedee** [comment]
Just a sample (all nagios checks works the same way)
root@monworker001:/var/db/newrelic-infra/custom-integrations# /usr/lib64/cmbmonit/plugins/check_load -w 0,3,2 -c 1,6,4
WARNING - load average: 0.01, 0.07, 0.08|load1=0.010;0.000;1.000;0; load5=0.070;3.000;6.000;0; load15=0.080;2.000;4.000;0;
PID USER %CPU COMMAND
1 root 0.0 /sbin/init
2 root 0.0 [kthreadd]
3 root 0.0 [ksoftirqd/0]
5 root 0.0 [kworker/0:0H]
7 root 0.0 [rcu_sched]
root@monworker001:/var/db/newrelic-infra/custom-integrations# /usr/lib64/cmbmonit/plugins/check_load -w 5,3,2 -c 6,6,4
OK - load average: 0.01, 0.07, 0.08|load1=0.010;5.000;6.000;0; load5=0.070;3.000;6.000;0; load15=0.080;2.000;4.000;0;

Thanks.

**Comment by haihongren** [comment]
I am not sure what metrics you are trying to get from the output. 
With the following sdeedee.yml config: 
`name: sdeedee
apis:
  - name: sdeedee
    commands:
      - run: cat sdeedee.abc
        split: horizontal
        row_header: 0
        set_header:
          [
            status,
            loadAverage1,
            loadAverage2,
            loadAverage1,
            load11,
            load12,
            load13,
            load14,
            load51,
            load52,
            load53,
            load54,
            load151,
            load152,
            load153,
            load154,
          ]
        regex_match: true
        split_by: '(\S+).*?(load average:)\s+(.*?),\s+(.*?),\s+(.*?)\|load1=(.*?);(.*?);(.*?);(.*?);\s+load5=(.*?);(.*?);(.*?);(.*?);\s+load15=(.*?);(.*?);(.*?);(.*?);'
`
I got the following result: 
`				{
					"event_type": "sdeedeeSample",
					"integration_name": "com.newrelic.nri-flex",
					"integration_version": "0.8.3-pre-3-gf5a6601-dirty",
					"load11": 0.08,
					"load12": 0.01,
					"load13": 0,
					"load14": 1,
					"load151": 0,
					"load152": 0.08,
					"load153": 2,
					"load154": 4,
					"load51": 0,
					"load52": 0.07,
					"load53": 3,
					"load54": 6,
					"loadAverage1": 0.07,
					"loadAverage2": 0.01,
					"status": "WARNING"
				},`

Please insert a blank line before the first line in the current output for multiple line output as Flex expects the metrics starts from the 2nd line onwards currently (for multi line output).  
For single line output, it should work fine. 

So this above yml config should work for the OK output. 
`OK - load average: 0.01, 0.07, 0.08|load1=0.010;5.000;6.000;0; load5=0.070;3.000;6.000;0; load15=0.080;2.000;4.000;0;`

Please let me know how you go with the yml config. 

`./nri-flex -config_file sdeedee.yml -pretty -verbose`

**Comment by haihongren** [comment]
In the above yml file, i am using "run: cat sdeedee.abc" to simulate your script output. 
the "sdeedee.abc" has the following content: 
`OK - load average: 0.01, 0.07, 0.08|load1=0.010;5.000;6.000;0; load5=0.070;3.000;6.000;0; load15=0.080;2.000;4.000;0;`

**Comment by sdeedee** [comment]
Hi @haihongren, thanks! I can go on with your example. The multi line output I can cover by removing newline characters so the output is always a single line.

Just two other questions related to variables. 

Is it possible to use variables in de flexConfig file? 

`/usr/lib64/cmbmonit/plugins/check_load -w @VARIABLES_ARG_WARNING -c @VARIABLES_ARG_CRITICAL`
@ARG_VARIABLES defined somewhere in the flexconfig file

Is it possible to reuse the run command and exit status of the command as variable to pass as attribute? Like in bash $? returns exit code of the command and $0 the command. To have:
`custom_attributes:
   command.exitcode: $?
   command.run: $0`

**Comment by haihongren** [comment]
**Please look at the following example:** 
- variable_store 
- custom_attributes
- ${var:myfile}

<pre>
name: sdeedee
variable_store:
  myfile: sdeedee.abc
  myCommand: cat
apis:
  - name: sdeedee
    commands:
      - run: ${var:myCommand} ${var:myfile}
        split: horizontal
        set_header:
          [
            status,
            loadAverage1,
            loadAverage2,
            loadAverage1,
            load11,
            load12,
            load13,
            load14,
            load51,
            load52,
            load53,
            load54,
            load151,
            load152,
            load153,
            load154,
          ]
        regex_match: true
        # split_by: '(\S+).*?(load average:)\s+(.*?),\s+(.*?),\s+(.*?)\|load1=(.*?);(.*?);(.*?);(.*?);\s+load5=(.*?);(.*?);(.*?);(.*?);\s+load15=(.*?);(.*?);(.*?);(.*?);'
        split_by: '(\S+).*?(load average:)\s+(.*?),\s+(.*?),\s+(.*?)\|load1=(.*?);(.*?);(.*?);(.*?);\s+load5=(.*?);(.*?);(.*?);(.*?);\s+load15=(.*?);(.*?);(.*?);(.*?);'
        custom_attributes:
          myCommand: ${var:myCommand}
          myFile: ${var:myfile}

</pre>

**I would also recommend you to look the following wiki document:** 

https://github.com/newrelic/nri-flex/wiki/Functions#store_variables
https://github.com/newrelic/nri-flex/wiki/Functions#lookup_file
https://github.com/newrelic/nri-flex/wiki/Functions#store_lookups
https://github.com/newrelic/nri-flex/wiki/Functions#add_attribute

- It does not capture exit code for Command at this moment, you can raise a feature request. 
- It does capture http return code if you are using url. For example: 
<pre>
name: nginxFlex
apis:
  - name: nginxStub
    url: http://127.0.0.1/nginx_status
</pre>

**Comment by sdeedee** [comment]
Thanks, that was what I needed.

**Comment by haihongren** [comment]
I am closing out this issue for now.  Thanks!
