### ISSUE TITLE
Flex IP Discovery on Kubernetes

### ISSUE THREAD

**Issue by wildcardlinux** [newrelic/nri-flex#364]
## Is your feature request related to a problem? Please describe.
Flex limitation on not being able to read the discovery environment variable. There's no hint of discovery being possible on the Flex source code.

## Feature Description
Flex to work with auto ip discovery on Kubernetes

## Describe Alternatives
https://discuss.newrelic.com/t/nri-flex-doesnt-work-with-discovery/184820

## Additional context
https://discuss.newrelic.com/t/nri-flex-doesnt-work-with-discovery/184820

## Priority
Really Want

**Comment by cristianciutea** [comment]
discovery it's a feature of the agent, it's not applied by the integrations.
The agent will read the integration configuration file and if the discovery configuration block is detected, will run the discovery mechanism and replace the tokens with the discovered variables.

**Comment by boogi** [comment]
@josemore is there possibility to run agent for discovery, and then start integration (e.g. nri-flex) to gather custom metrics on those discovered nodes?

**Comment by josemore** [comment]
Yes, that should be possible. Flex should behave as any other integration (though not listed here, we'll improve this). See: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes
