### ISSUE TITLE
Flex not working though API call works with Curl -k

### ISSUE THREAD

**Issue by Santu439** [newrelic/nri-flex#365]
Hi ,

I’m trying to do Ambari API integration using curl however facing with certificate error. I’m able to access metrics using curl without certificates by using option “ curl -k”. However when I try to integrate using flex, it is expecting certificates. My understanding is that flex should treat it as unsecured and allow to fetch metrics if we don’t give certificates path. 

Please advise on how to fix this or an alternative flex usage to use unsecured “curl -k”

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
