### ISSUE TITLE
Add support for Oracle DB

### ISSUE THREAD

**Issue by khpeet** [newrelic/nri-flex#379]
## Is your feature request related to a problem? Please describe.
Ability to connect and run queries against Oracle DBs

## Feature Description
The nri-oracledb integration does not allow for running of custom queries without also collecting lots of unwanted metrics. Flex seems like a lightweight option for customers that only want to run specific queries and report the results back to New Relic. There is a client library available that does not require any Oracle Instant Client to be installed as a dependency: https://github.com/sijms/go-ora

## Describe Alternatives
nri-db: https://github.com/newrelic-experimental/nri-db

This uses deprecated dependencies and does not have official support. Java is also much heavier that Go. This solution also does not allow for flexibility in specifying polling intervals per unique db query.

## Priority
**Blocker**

**Comment by davidgit** [comment]
Hi,

We consolidated multiple channels that were used to file Feature Requests (FRs). In the spirit of improving the visibility of FRs, we believe it's best for them to be submitted through the [New Relic Issue Tracker](https://github.com/newrelic/Github_JIRA_sandbox/blob/main/.github/ISSUE_TEMPLATE/issues.newrelic.com). This single tool will enable better aggregation of FRs and improve our ability to synthesize requests and provide better value to our users. You can see and vote for other FRs submitted by all users.

Please provide a link to this GitHub issue when submitting your feature request.

Thanks!
