### ISSUE TITLE
Extra middle whitespace in `name: nri-flex` throws an error

### ISSUE THREAD

**Issue by ciranor** [newrelic/nri-flex#390]
When writing the YML config file, it doesn't accept extra whitespace on the `name: nri-flex` line.

e.g. This will work
```
integrations:
  - name: nri-flex
    interval: 3600s
    config:
      name:     whatever
      ...
```
But this will not:
```
integrations:
  - name:     nri-flex
    interval: 3600s
    config:
      name:     whatever
      ...
```
And will throw an error `config: flexConfig requires name`, which was tricky to understand given that, as far as I was concerned, there *was* a `name:` field on each level. (I hit this while writing my YML file in a human-formatted/tidy/OCD way).

**Comment by rogercoll** [comment]
@ciranor Thanks for opening this issue. As you denoted, there is a bug in how the YML for V4 configurations is parsed. We are going to work on the fix asap and keep you updated in this issue.
