### ISSUE TITLE
Installation requires "restart"; not "start"

### ISSUE THREAD

**Issue by cah-zack-mutchler** [newrelic/nri-flex#41]
ref: [https://newrelic-flex.s3-ap-southeast-2.amazonaws.com/install_linux_s3.sh](https://newrelic-flex.s3-ap-southeast-2.amazonaws.com/install_linux_s3.sh)

from the [README.md](https://github.com/newrelic/nri-flex#installation) the installation method for Flex is as follows: 
`sudo bash -c "$(curl -L https://newrelic-flex.s3-ap-southeast-2.amazonaws.com/install_linux_s3.sh)"`

the ending of that installation shell script has this snippet: 
```
echo "### Starting NR Infrastructure Agent"
if [ -f /etc/systemd/system/newrelic-infra.service ]; then
    service newrelic-infra start
fi
if [ -f /etc/init/newrelic-infra.conf ]; then
    initctl start newrelic-infra
fi
```

The expected outcome of this is that any new Flex Configs added to `/var/db/newrelic-infra/custom-integrations/flexConfigs/` would automatically start sending data to Insights. However, if the infrastructure agent is already running, the **"start"** command doesn't work and a **"restart"** (_or "stop/start"_) is required before data is sent.

**Comment by Kav91** [comment]
hey Zack, the script should stop the agent prior to the block of code you've mentioned
https://github.com/newrelic/nri-flex/blob/master/scripts/install_linux_s3.sh#L24

have you had situations where the agent has not stopped, before attempting to start again?

Also with the new work that has been done with the infrastructure agent we could make use of the hot reloading capabilities and not worry about start/stopping.

**Comment by cah-zack-mutchler** [comment]
Thanks Kav;

Yesterday I installed on 4 servers using this method: 
`sudo bash -c "$(curl -L https://newrelic-flex.s3-ap-southeast-2.amazonaws.com/install_linux_s3.sh)"`

With all 4, I noticed that after a successful installation, no events were being sent to Insights until I restarted the Infrastructure agent.

workflow: 
1. install Flex via snippet from README.md above
2. create 1 or more YAML configs in the default `/flexConfigs` directory
3. execute the config via: `./nri-flex --verbose --config_file "flexConfigs/configName.yml"` to validate data collection

This is where I noted the lack of data actually being sent into Insights. One the first server I waited about 20 minutes before restarting the agent to ensure it was not a latency issue. 

On all 4 servers, data immediately began flowing on reboot of the infrastructure agent and any subsequent changes/removals/additions of flex configs would automatically send data as expected.

inventory of sample servers: 
SUSE Linux Enterprise Server 11 SP4
Infrastructure Agent Versions 1.4.9 and 1.5.51

**Comment by Kav91** [comment]
got it, one more question was the infrastructure agent sending any of the default events at all either? 
eg. SystemSample, ProcessSample etc. 
or was that also not being sent till you did the restart?

thx

**Comment by cah-zack-mutchler** [comment]
to my knowledge yes, the standard infrastructure metrics were still being sent correctly.

**Comment by Kav91** [comment]
As the linux infrastructure agent now comes with Flex bundled this issue can be closed.

**Comment by karuppiah7890** [comment]
@Kav91 , when you say "bundled", do you mean that infrastructure agent binary has nri-flex code too? I didn't notice it in the `go.mod` of infrastructure agent. Or do you mean nri-flex is installed as part of infrastructure agent installation? But that doesn't seem to be the case for installation through tar ball. Or does infrastructure agent pull nri-flex binary when required? 🤔

**Comment by Kav91** [comment]
@karuppiah7890 the code is not added, but the Flex binary itself is pulled in. I don't believe it will be pulled in during a tarball based install, since we typically recommend to install via the automated methods.

You will find the `nri-flex` binary at these paths if it was automatically bundled.

If you are managing your install manually, then you could take the appropriate binary from the releases section and place the Flex binary into the same path.
```
# Linux
/var/db/newrelic-infra/newrelic-integrations/bin/

# Windows
C:\Program Files\New Relic\newrelic-infra\newrelic-integrations\
```
