### ISSUE TITLE
Sampling rate to New Relic does not go below 15s

### ISSUE THREAD

**Issue by kristiyanbks** [newrelic/nri-flex#426]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
The sampling rate does not  go below 15s

Close if this is treated as a new feature. 

## Expected Behavior
To be able to manage the sampling rate

Using Flex did not see a possibility to change the sampling rate. 

## Steps to Reproduce

Using the following Flex example; https://github.com/newrelic/nri-flex/blob/master/examples/windows/windows-perfmon.yml

1. Go to New Relic's Flex dir
2. Edit windows-perfmon.yml

## Your Environment
Windows Server 2019 with New Relic Infra Agent 1.36.0

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by davidgit** [comment]
Hi,

We consolidated multiple channels that were used to file Feature Requests (FRs). In the spirit of improving the visibility of FRs, we believe it's best for them to be submitted through the [New Relic Issue Tracker](https://issues.newrelic.com). This single tool will enable better aggregation of FRs and improve our ability to synthesize requests and provide better value to our users. You can see and vote for other FRs submitted by all users.

Please provide a link to this GitHub issue when submitting your feature request.

Thanks!
