### ISSUE TITLE
Nri flex not sending the data

### ISSUE THREAD

**Issue by ankitchaubey** [newrelic/nri-flex#43]
I am running flux in docker container and rabbitmq external check is running in the container  I am getting yaml error and system matrix is not going 

> >/ # /usr/bin/newrelic-infra -config s
> INFO[0000] runtime configuration agentUser=root component=“New Relic Infrastructure Agent” executablePath= maxProcs=1 pluginDir="[/etc/newrelic-infra/integrations.d /var/db/newrelic-infra/integrations.d]"
> INFO[0000] Checking network connectivity… component=AgentService service=newrelic-infra
> INFO[0000] Initializing component=AgentService elapsedTime=375.676437ms service=newrelic-infra
> WARN[0000] can’t load integrations file component=integrations.Manager error=“yaml: unmarshal errors:\n line 4: cannot unmarshal !!seq into string” file=nri-flex-config.yml folder=/etc/newrelic-infra/integrations.d
> INFO[0000] New Relic Infrastructure Agent Running component=AgentService elapsedTime=551.206809ms service=newrelic-infra
> INFO[0000] Starting up agent… component=Agent
> WARN[0000] failed to start monitoring for shutdown component=NotificationHandler error=“no systemd found”
> INFO[0000] Agent plugin plugin=metadata/attributes

**nri-flex-config-linux.yml**

> integration_name: com.newrelic.nri-flex
> 
> instances:
> – name: nri-flex
> command: metrics

LOGS INSIDE THE CONTAINER 

> /var/db/newrelic-infra/custom-integrations # ./nri-flex -config_file flexConfigs/rabbitmq-http.yml  -verbose -pretty
> INFO[0000] com.newrelic.nri-flex                         GOARCH=amd64 GOOS=linux version=0.8.5
> DEBU[0000] config: git sync configuration not set       
> DEBU[0000] discovery: finding flex container id          output=/docker/6712f62228db8e89XX
>cread=/proc/1/cpuset
> DEBU[0000] discovery: flex container id found            containerId=6712f62228db8e89XXX
> DEBU[0000] docker: setting client with API version negotiation 
> DEBU[0000] discovery: containers 4 filtered containers 3 
> DEBU[0000] discovery: no configs found                   dir=flexContainerDiscovery/ message="if you are using v2 discovery then ignore"
> INFO[0000] flex: config files loaded 1                  
> DEBU[0000] config: running async                         name=rabbitFlex
> DEBU[0000] config: processing apis                       apis=0 name=rabbitFlex
> DEBU[0000] config: finished processing apis              apis=0 name=rabbitFlex
> INFO[0000] flex: completed processing                    configs=1
> {
> 	"name": "com.newrelic.nri-flex",
> 	"protocol_version": "3",
> 	"integration_version": "0.8.5",
> 	"data": [
> 		{
> 			"metrics": [
> 				{
> 					"event_type": "flexStatusSample",
> 					"flex.ContainerId": "6712f62228db8e89XXX",
> 					"flex.Hostname": "ip-10-19-XX",
> 					"flex.IntegrationVersion": "0.8.5",
> 					"flex.counter.ConfigsProcessed": 1,
> 					"flex.counter.EventCount": 0,
> 					"flex.counter.EventDropCount": 0,
> 					"flex.time.elaspedMs": 6,
> 					"flex.time.endMs": 1576166271517,
> 					"flex.time.startMs": 1576166271511
> 				}
> 			],
> 			"inventory": {},
> 			"events": []
> 		}
> 	]
> }

**Comment by Kav91** [comment]
Hi @ankitchaubey on this line you referred too

> WARN[0000] can’t load integrations file component=integrations.Manager error=“yaml: unmarshal errors:\n line 4: cannot unmarshal !!seq into string” file=nri-flex-config.yml

It appears the yaml is not formatted correctly, are you able to confirm your yaml files are correctly formatted. You can use something like http://www.yamllint.com/ to validate.

If that does not resolve the issue, are you able to share your config files being used?

**Comment by Kav91** [comment]
Closing - inactive 2 weeks no response.
