### ISSUE TITLE
Port data collection interval issues using flex

### ISSUE THREAD

**Issue by dokyun-kim** [newrelic/nri-flex#49]
Hello,
I am using flex on windows OS to collect port data. However, the collection interval is experiencing an increasing issue.

- Provider: AzureVirtualMachine
- Windows OS: Windows Server 2016 Datacenter
- NewRelic Infra Agent: 1.8.14
- nri-flex: nri-flex-windows-0.8.5

Using Flex to collect port data.

Although the interval in the nri-flex-definition.yml configuration file is set to 30 seconds.
However, when queried from INSIGHTS, the data collection interval continues to increase from 40 seconds to 1 minute to 2 minutes.

1. VM-port.yml
![01, port-yml](https://user-images.githubusercontent.com/59544391/71788613-512eae80-3067-11ea-8a40-5851f250bdbf.png)

2. nri-flex-definition.yml
![02, nri-flex-definition yml](https://user-images.githubusercontent.com/59544391/71788622-5f7cca80-3067-11ea-948a-0e9c7b0b35b5.png)

3. The system, network, and storage utilization rate of the server is not high.
![03, System Usage](https://user-images.githubusercontent.com/59544391/71788626-6b688c80-3067-11ea-9117-e9ad5fef2e12.png)

![04, Network Usage](https://user-images.githubusercontent.com/59544391/71788627-6e637d00-3067-11ea-8907-53b890ec9f80.png)

![05, Storage Usage](https://user-images.githubusercontent.com/59544391/71788630-715e6d80-3067-11ea-9a4d-717bc2949d38.png)

4. The 8080,8090,8585,14233 set in the VM-port.yml file have the same issue, and the 14233 port is used as an example to show the data collection interval.
When the port data was first collected, it was collected about 40 seconds interval.
![06, insight - 1](https://user-images.githubusercontent.com/59544391/71788647-889d5b00-3067-11ea-9ece-a01733767932.png)

5. Over time, data is collected about 1 minutes interval.
![06, insight - 2](https://user-images.githubusercontent.com/59544391/71788659-9a7efe00-3067-11ea-94e0-f7bf09e08507.png)

6. Currently, data is collected about 2 minutes interval.

Although the interval is set to 30 in the nri-flex-definition.yml configuration file  
Why does the increase port data collection interval continue?

![07, insight - 3](https://user-images.githubusercontent.com/59544391/71788665-a4a0fc80-3067-11ea-9375-bd903813ced8.png)

Thank you

**Comment by Kav91** [comment]
Hi, I think I spoke with another Relic internally today in regards to this issue you were experiencing.

On point number 2, integrations do not execute on the dot of each 30sec interval. It is 30seconds from after the time of completion. So if you had Flex doing a job that takes 15seconds, the next interval is after 15s + 30s.  So the behaviour you are seeing is correct and is actually something to do with the infrastructure agent and not Flex itself.

The purpose behind this behaviour is to cater for situations where integrations could potentially take a very long or unexpected time to complete before the next interval starts so we avoid unpredictable queuing behaviours.

The suggestion that was provided was to use the lookup file functionality.
https://github.com/newrelic/nri-flex/wiki/Functions#lookup_file
https://github.com/newrelic/nri-flex/blob/master/examples/flexConfigs/port-test-with-lookup.yml

The lookup file will split each port test you have into a separate config file dynamically. 
Flex configs are executed asynchronously meaning that all port tests would fire at once, rather then waiting for each to finish before proceeding to the next. 
This way the delay will be at most be the minor execution time + the timeout period given anything does timeout.

Let me know if the above clears up your question, and if the lookup file solution works for you .

**Comment by dokyun-kim** [comment]
Hello Kav91, Thank you for your answer.

I tried using the lookup type but there was still a delay.
Currently I received a response from another NewRelic engineer to reinstall the infra agent.
Because of the "cannot find configuration" and "unmarshal" errors in the log files of the NewRelic 1.8.14 agent.

I'll check the issue after reinstalling the latest version of NewRelic Infra Agnet.

Thank you!!

**Comment by Kav91** [comment]
No problem.

If you still have issues with the lookup file option, just share your Flex Config, and the lookup file, so we can best try to replicate and debug it.
