### ISSUE TITLE
Sybase DB configuration using nri-flex unable to connect to the database

### ISSUE THREAD

**Issue by shivanikash** [newrelic/nri-flex#512]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
JIRA: https://new-relic.atlassian.net/browse/NR-288615
I am trying to configure the Sybase DB integration using flex but facing below error message (_please see the attachement_) and its not able to connect to the database. 

errorMsg="error opening test connection: go-ase: error logging in: error building login payload: error writing appname: string 'replace github.com/newrelic-experimental/go-dblib =\u003e github.com/newrelic-experimental/go-dblib \u003cnewVersion\u003e\n' is too large, must be at most 30 bytes long"

## Expected Behavior
Custom query configured in the flex yaml to be executed and output data visible in Newrelic portal.

## Steps to Reproduce
Install the newrelic infrastructure agent and configure the flex yaml file as below. 
integrations:
  - name: nri-flex
    config:
      name: sybaseMetrics
      apis:
        - database: sybase
          db_conn: ase://user:pass@host:port/
          logging:
            open: true
          custom_attributes:
            host: myDBserver
          db_async: true
          db_queries:
            - name: sybaseServerName
               run: SELECT * FROM data

## Your Environment
Newrelic Infrastructure agent version - 1.53.0
Operating System - RHEL 8x

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/87ae2e77-2acd-4ea4-8e1f-f3d13fffd5fc">

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
