### ISSUE TITLE
Functions to trim keys and values

### ISSUE THREAD

**Issue by bokken** [newrelic/nri-flex#57]
It would be helpful to have functions to trim leading/trailing white space from keys and values.
From an order of operations perspective, this should probably be done very early on and certainly prior to the existing convert_space function, which would still be useful for handling spaces within keys.

**Comment by Kav91** [comment]
@bokken would the value_parser solve your needs?
`Find keys using regex, and again use regex to pluck the first found value out`
https://github.com/newrelic/nri-flex/wiki/Functions#value_parser

**Comment by bokken** [comment]
@Kav91, while it certainly would be possible to accomplish a trim with regex, I think it would require both lookaheads and lookbehinds to avoid matching the leading/trailing white space. For most folks, that is getting a bit complicated to mentally reason about to ultimately accomplish a relatively simple task.

If the value_parser supported a find/replace type syntax where a matching group could be referenced, that would be an easier way to accomplish this with regex.

**Comment by haihongren** [comment]
@bokken 

We have another function `value_mapper` to do this. It supports regex, including matching group using the format of $1, $2, etc. Here is an example. 

```yml

    value_mapper:
      title:
        - (Service Status)=>Normal
        - (Informational message)=>$1 - Warning
        - (Service degradation)=>$1 - Warning
        - (Service disruption)=>$1 - Down
        - (Service is operating normally)=>$1 - Normal
