### ISSUE TITLE
Merge with JoinKey to work with stored lookups

### ISSUE THREAD

**Issue by bokken** [newrelic/nri-flex#62]
Enhance the Merge/JoinKey functionality(https://github.com/newrelic/nri-flex/pull/35) to work with store_lookups.

**Comment by haihongren** [comment]
This is supported from 0.9.6 version.

**Comment by bokken** [comment]
@haihongren, thanks for the update. I see that nri-flex is now included in the newrelic-infra agent. How can one determine which version of nri-flex is in which version of the newrelic-infra agent?

**Comment by haihongren** [comment]
`nri-flex -verbose ` should show the version info of Flex.
