### ISSUE TITLE
error calling MarshalJSON for type / json: unsupported value: +Inf

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-flex#66]
## Details

- version=0.9.3
- GOARCH=amd64
- GOOS=linux
- Kubernetes
- Helm Charts

### Redacted Log

[error_json_marshal.txt](https://github.com/newrelic/nri-flex/files/4106674/error_json_marshal.txt)

## Summary

Using the integration for Consul, there is an error that happens when marshaling the JSON that is to be sent via the infra-agent.

## Error Message

```text
FATA[0000] flex: unable to publish                       err="error marshalling to JSON: json: error calling MarshalJSON for type *metric.Set: json: unsupported value: +Inf"
```

**Comment by Kav91** [comment]
Fix added in https://github.com/newrelic/nri-flex/releases/tag/v0.9.4
Will reopen if it is still occurring.

Thanks
