### ISSUE TITLE
Send an event to Insights when http request fails

### ISSUE THREAD

**Issue by prodjito** [newrelic/nri-flex#75]
Right now, an HTTP request failure is only visible in the form of debug statements that can only be seen when Flex is run on verbose mode.

https://github.com/newrelic/nri-flex/blob/master/internal/inputs/http.go#L151
This appears to be where http error handling logic resides. I'm wondering if this is a good place to add additional logic to push http errors to Insights for users who may want to alert off of failed http requests. This is a common use case for users who use Flex for http health checks.

**Comment by ardias** [comment]
Hi @prodjito thank you for the issue. We will take it into consideration internally as it seems to be a good idea, not only for Http but for other errors also.
