### ISSUE TITLE
NRI-FLEX Version missing nri-flex.exe for windows

### ISSUE THREAD

**Issue by srikanthvamaraju** [newrelic/nri-flex#91]
Hello,
The new version of NRI-FLEX is missing some files like the exe and nri-flex-definition.yml files.
I follow the instructions and try to download the release from here. 
Can you please point me out to a stable build. 

The version i try to use is 
[https://github.com/newrelic/nri-flex/releases/tag/v0.9.7]

**Comment by ardias** [comment]
Hi @srikanthvamaraju 
Thanks for lettings us know. We'll fix it asap
